"""Cross-family realism critic.

Generation uses DeepSeek; this critic uses Moonshot Kimi K2.6 (different
lab, different pretraining corpus). The critic plays a senior practitioner
in the target occupation and rates how realistic the task feels — would a
14-year-veteran lawyer / 12-year analyst / 11-year engineer have actually
written this?

Rubric for the critic itself is grounded in industry conventions, not
LLM-invented criteria.
"""

from __future__ import annotations

import logging

from pydantic import BaseModel, Field

from pipeline.config import settings
from pipeline.llm import default_client
from pipeline.scenario.task_candidate import TaskCandidate

logger = logging.getLogger(__name__)


class RealismScore(BaseModel):
    workplace_voice: int = Field(ge=1, le=10, description="Does the prompt sound like a real boss wrote it? 10 = indistinguishable from a real GDPval task. 1 = obvious AI generation.")
    domain_specificity: int = Field(ge=1, le=10, description="Does it use field-specific jargon, formats, conventions correctly? 10 = a domain reader would not flinch.")
    rubric_quality: int = Field(ge=1, le=10, description="Are the rubric items atomic, specific, and machine-checkable? 10 = matches GDPval style: 45-55 items, mostly +1/+2 points (60-90 total), has exact-match items, ~1% penalty items, format/reference/data emphasis. 8 = good but too many high-point items or missing exact-match checks.")
    fact_grounding: int = Field(ge=1, le=10, description="Are entities/dates/numbers/citations real and consistent? 10 = grounded throughout, no invented facts.")
    overall: int = Field(ge=1, le=10, description="Aggregate realism. 10 = ship it. ≤4 = reject.")
    issues: list[str] = Field(description="Concrete problems found. ≤4 items, each ≤25 words. Empty if none.")
    suggestions: list[str] = Field(default_factory=list, description="≤3 specific edits, each ≤20 words.")


_OCCUPATION_PERSONAS = {
    "lawyer": (
        "You are a partner at a top-tier law firm with 20 years of litigation experience. "
        "You hire junior associates and review their work. You can spot AI-generated legal "
        "writing in 30 seconds: vague conclusions, made-up case citations, missing Bluebook "
        "formatting, generic phrases like 'navigate the complexities'."
    ),
    "financial_analyst": (
        "You are a managing director at a bulge-bracket investment bank with 18 years of "
        "experience. You have reviewed thousands of analyst deliverables. You know what "
        "real internal models look like: they have circular references, sensitivity tables "
        "tied to assumption cells, balance sheets that actually balance. You spot fakes "
        "instantly — invented ticker fundamentals, generic 'industry analysis' fluff, "
        "rubric items like 'demonstrates analytical rigor'."
    ),
    "software_engineer": (
        "You are a Principal Engineer at a major tech company with 15 years of experience "
        "across infrastructure and product. You review hundreds of design docs and PR "
        "descriptions per quarter. You can tell AI-generated work by: vague performance "
        "claims without numbers, made-up file paths and method names, generic test plans "
        "(\"add unit tests\" with no specifics), references to issues that don't exist."
    ),
}


_REALISM_SYS = """{persona}

You are reviewing a candidate task that was generated by a synthetic data pipeline. Your job is to score how realistic it feels — would this task pass for one written by a real practitioner with 14+ years of experience?

Use a 1-10 Likert scale on each dimension. Be calibrated, not lenient: a 10 means indistinguishable from real GDPval; an 8 means good but you can tell something is slightly off; a 5 means clearly synthetic; a 2 means obvious AI generation.

Be ruthless. Reviewers will read your scores; if you give 9s to mediocre work, you lose credibility.

Common failure modes to watch for:
  - "AI tells": "navigate the complexities", "in today's fast-paced world", "delve into"
  - Vague rubric items ("demonstrates quality", "is comprehensive")
  - Invented facts not anchored to real entities/dates/citations
  - Overlong, hedge-heavy prose ("It is important to note that...")
  - Generic deliverable specs ("write a report") instead of GDPval-specific format demands
"""


_REALISM_USER_TMPL = """## Candidate Task

### Prompt
{prompt}

### Rubric ({n_rubric} items, {total_pts} total points)
{rubric}

### Canonical pinned facts
{facts}

Score this candidate and return JSON RealismScore."""


def critique(
    task: TaskCandidate,
    model: str | None = None,
) -> RealismScore:
    client = default_client()
    model = model or settings().critic_model
    persona = _OCCUPATION_PERSONAS[task.occupation]
    sys_prompt = _REALISM_SYS.format(persona=persona)

    rubric_text = "\n".join(
        f"  [+{r.score}] ({r.category}) {r.criterion}" for r in task.rubric
    )
    facts_text = "\n".join(
        f"  [{f.id}] {f.kind}: {f.value}{(' ' + f.unit) if f.unit else ''}"
        for f in task.canonical.facts[:10]
    )
    user = _REALISM_USER_TMPL.format(
        prompt=task.prompt,
        n_rubric=len(task.rubric),
        total_pts=task.total_rubric_points(),
        rubric=rubric_text,
        facts=facts_text,
    )

    logger.info("realism critique on %s using %s", task.candidate_id, model)
    return client.chat_structured(
        [
            {"role": "system", "content": sys_prompt},
            {"role": "user", "content": user},
        ],
        RealismScore,
        model=model,
        temperature=0.3,
        max_tokens=4096,
    )
